name: NodeJS Test

on:
  push:

jobs:

  build_and_test_ncc_0_23_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.JS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup NCC 0.23.0 package-lock.json
        run: mv package-lock.ncc-0-23-0.json package-lock.json
      - name: Install Node Dependencies
        run: npm ci
        env:
          CI: TRUE
      - name: Run ESLint
        run: npm run lint
      # The project is build in a pretest hook
      - name: Run unit tests
        run: npm run test

  build_and_test_ncc_0_24_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.JS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup NCC 0.24.1 package-lock.json
        run: mv package-lock.ncc-0-24-1.json package-lock.json
      - name: Install Node Dependencies
        run: npm ci
        env:
          CI: TRUE
      - name: Run ESLint
        run: npm run lint
      # The project is build in a pretest hook
      - name: Run unit tests
        run: npm run test